name = "cloudflare-vless-trojan"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "cloudflare-vless-trojan"

# 需要添加你的账户信息
# account_id = "your-account-id"
# workers_dev = true
